import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import "./tailwind.css";
import Navbar from "@/components/Navbar";

const plus = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "British Columbia Youth Developer Collective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plus.className}`}>
        <div className="flex flex-col items-center w-screen">
          <div className="flex flex-col items-center w-full max-w-[1536px] px-8">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
